-- Q.7.1

-- CREATING ACCOUNT TABLE:

CREATE TABLE ACCOUNT (
ACCOUNT_NUMBER NUMBER,
BALANCE NUMBER CONSTRAINT MIN_BALANCE CHECK (Balance > 1000)
);


-- INSERING VALUES INTO ACCOUNT TABLE:

INSERT INTO ACCOUNT VALUES(101, 10000);
INSERT INTO ACCOUNT VALUES(102, 20000);
INSERT INTO ACCOUNT VALUES(103, 30000);
INSERT INTO ACCOUNT VALUES(104, 40000);
INSERT INTO ACCOUNT VALUES(105, 50000);


-- PL/SQL BLOCK FOR THE PROCESS:

SET SERVEROUTPUT ON
DECLARE

v_accno number;
v_withdraw number;

BEGIN

v_accno := &v_accno;
v_withdraw := &v_withdraw;

Withdraw_Money(v_accno, v_withdraw);

END;
/